openapi: 3.0.3
info:
  title: Spotifete Api
  version: 0.0.1
servers:
  - url: localhost:3000
    description: dev server
tags:
  - name: authentication
    description: Authentication related routes
  - name: listeningSession
    description:  ListeningSession related routes
paths:
  /api/v2/auth/session/new:
    get:
      tags:
        - authentication
      operationId: newAuthenticationSession
      responses:
        "200":
          description: Successful created session
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/NewSessionResponse"
        "500":
          $ref: "#/components/responses/ServerError"

  /api/v2/auth/session/id/{sessionId}/is-authenticated:
    get:
      tags:
        - authentication
      operationId: isSessionAuthenticated
      responses:
        "200":
          description: Session is authenticated
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/IsSessionAuthenticatedResponse"
        "401":
          description: Session is not authenticated
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/IsSessionAuthenticatedResponse"
        "404":
          description: Unknown authentication session
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/ErrorResponse"
    parameters:
      - name: sessionId
        required: true
        in: path
        schema:
          type: string
  /api/v2/auth/session/id/{sessionId}/invalidate:
    patch:
      tags:
        - authentication
      operationId: invalidateAuthenticationSession
      responses:
        "204":
          description: Session was sucessfully invalidated
components:
  responses:
    ServerError:
      description: An error occured
      content:
        "application/json":
          schema:
            $ref: "#/components/schemas/ErrorResponse"
  schemas:
    NewSessionResponse:
      type: object
      properties:
        spotify_authentication_url:
          type: string
        spotifete_session_id:
          type: string
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
    IsSessionAuthenticatedResponse:
      type: object
      properties:
        authenticated:
          type: boolean
      required:
        - authenticated
